### ISSUE TITLE
group and sort order ignored

### ISSUE THREAD

**Issue by patrickschoeberlein** [petersirka/mongobuilder#1]
Hi, i was just using mongobuilder to select lots of tire records from mongodb for a price comparison website. I ordered them by price to show the cheapest tire first. Since every tire is saved one time for each data-provider, i have multiple offers for each tire. I grouped them by EAN (european article number) after sorting to show the cheapest offer for each tire.

However, i found that in mongobuilder\index.js the method `MongoBuilder.prototype.aggregate = function(collection, options, callback) { ... }` does not consider my sort/group order and always uses group before sort. When using the aggregate $first i don't get the cheapest tire, because my records were not sorted by price before grouping. Instead, the result of my group command gets sorted, but i have no control over the record thats returned with $first or $last.

Here is some of my source code

```
    var builder = new MongoBuilder();
   ...
    builder.sort('Price', true);

    builder.group('_id.EAN', 'count.$sum.1');
    builder.group('_id.EAN', 'id.$first.id');
    builder.group('_id.EAN', 'EAN.$first.EAN');
    builder.group('_id.EAN', 'Price.$first.Price');
    builder.group('_id.EAN', 'Img_url.$first.Img_url');

    builder.aggregate(DB('tires'), function (err, docs) {
      callback(docs);
    });
```

Here is my current "workaround" for MongoBuilder.prototype.aggregate

```
MongoBuilder.prototype.aggregate = function(collection, options, callback) {
    var self = this;

    if ((options === undefined && callback === undefined) || (typeof(options) === OBJECT && callback === undefined))
        callback = NOOP;

    if (typeof(options) === FUNCTION) {
        callback = options;
        options = undefined;
    }

    var agg = self._agg;
    if (self.onAggregate)
        self.onAggregate(agg);

    var keys = Object.keys(agg);
    var pipeline = [];

    if (self._filter)
        pipeline.push({ $match: self.getFilter() });

        // here is the part where i added something!
        //**********************************************************
    if (self._sort)
        pipeline.push({ $sort: self._sort });
        //**********************************************************

    for (var i = 0, length = keys.length; i < length; i++) {
        var tmp = {};
        tmp[keys[i]] = agg[keys[i]];
        pipeline.push(tmp);
    }

    if (self._sort)
        pipeline.push({ $sort: self._sort });

    if (self._take > 0)
        pipeline.push({ $limit: self._take });

    if (self._skip > 0)
        pipeline.push({ $skip: self._skip });

    if (options)
        collection.aggregate(pipeline, options, callback);
    else
        collection.aggregate(pipeline, callback);

    return self;
};
```

I guess, to actually fix this bug, Mongobuilder would have to save the order in which .sort and .group are called and use this order when adding commands to `pipeline`.

**Comment by petersirka** [comment]
Hi @patrickschoeberlein,
thank you. I have created a new module `SQL Agent` with MongoDB support (similar features) and I want to remove or move this repository to another developer. SQL Agent is a better module and I recommend it to you.

**SQL Agent:**
https://github.com/petersirka/node-sqlagent#push-only-for-mongodb

So we have three ways:
1. you can fix this problem (I can add you as contributor)
2. I can transfer the repository e.g. to you
3. I'll update readme about end of support

Really sorry!
Thank you!

**Comment by patrickschoeberlein** [comment]
Hi @petersirka, sorry for the late reply.
Currently i would choose option 3... I would prefer using `SQL Agent` to maintaining `MongoBuilder` myself. My "fast" solution works fine for now, but for future projects i will definitely use `SQL Agent`.
