### ISSUE TITLE
Field option not work

### ISSUE THREAD

**Issue by dacrhu** [petersirka/mongobuilder#2]
Hi Peter,

I have a schema:

    schema.setQuery(function(error, options, callback) {
        let mongoBuilder = new F.mb.MongoBuilder();
        mongoBuilder.field('email', false);
        mongoBuilder.page(options.page, options.max);
        mongoBuilder.find(DATABASE('users'), callback);
    });

But output contains email field.

MongoBulider output in console:

MongoBuilder {
  _filter: null,
  _sort: null,
  _skip: 0,
  _take: 10,
  _scope: 0,
  _agg: null,
  _upd: null,
  _fields: { email: 0 },
  onFilter: null,
  onUpdate: null,
  onAggregate: null,
  onInsert: null }

If I try fields:
mongoBuilder.fields('email', 'name');

then output contains all of fields from collection.

Do I do something wrong?

Thank you,
David

**Comment by petersirka** [comment]
Hi @dacrhu,
can you use __MongoDB__ in [SQL Agent](https://github.com/totaljs/node-sqlagent)?

**Comment by dacrhu** [comment]
Thank you @petersirka , i try with it.

**Comment by dacrhu** [comment]
Ok, with SQL Agent working fine. Thank you!
